#!/bin/bash
# https://git.jayvii.de/Scripts/NeoVim-Xterm
# V 0.1

if ! [ $(ls /usr/bin/xterm) ]; then
	echo "[ERROR] neovim-wrapper requires xterm"
	exit 1;
fi

# run xterm with following arguments (run "man xterm" for more information)
XTERM_ARGS="+ah +ai -aw -b 1 -bc +cm -cu -name NeoVim -title NeoVim -u8"
# run xterm with following fonts (run "man xfontsel" for more information)
XTERM_FONTS="-fs 12 -fa *-fixed-*-*-*--8 -fb *-fixed-bold-*-*-*-8"

# run nvim with specified xterm-args
xterm ${XTERM_ARGS} ${XTERM_FONTS} -e nvim
